### ISSUE TITLE
SSD Extractor ".h" file Linking Error

### ISSUE THREAD

**Issue by ankit7sethi** [richardstechnotes/UnityARKitDetection#1]
On creating build from Unity and adding the model file, it is giving linking error for the line #import "ssd_mobilenet_feature_extractor.h" in Vision Bridging Header.
<img width="1087" alt="screenshot 2019-01-16 at 5 17 49 pm" src="https://user-images.githubusercontent.com/3744778/51247322-c3b80180-19b2-11e9-8792-5888c5e476fc.png">

**Comment by r-b-us** [comment]
That file is automatically generated when you add the ssd_mobilenet_feature_extractor.mlmodel. Did you add the model file File, Add files to... command? It should have appeared at that point.

**Comment by oliverellmers** [comment]
Hello, 

I have come across the same error in xcode.

I had a dig around the SSDMobileNet_CoreML repo and could not find the missing "_ssd_mobilenet_feature_extractor.h" header file either. Has this been resolved?

Thanks,

Oliver

**Comment by r-b-us** [comment]
As I said in the earlier response, this pseudo file is automatically generated by Xcode when the model file is added using the process described in the README. That's why it isn't in the repo.

**Comment by oliverellmers** [comment]
Thanks for getting back so quickly. I followed the instructions as outlined
and still have the same error. Could it be an xcode version issue?

Cheers,

Oliver

**Comment by r-b-us** [comment]
Don't know. I am using 10.1 (10B61) in case that's helpful.

If the model has been added correctly, you should see something like this:

![screen shot 2019-02-05 at 2 17 44 pm](https://user-images.githubusercontent.com/613192/52298500-156c0000-2951-11e9-90f3-a44c429ff31e.png)

**Comment by oliverellmers** [comment]
Thanks for this,

I managed to solve the issue in the end.

Once the file has been added to the project using your described steps, you then need to select the file in the left hierarchy and on the right hand side use the localisation features to confirm the file has been added to the project directory. 

I now have the project running on an iPad air 2 out of xcode version 10.1 (10B61)

Cheers,

Oliver

**Comment by r-b-us** [comment]
Excellent.
